# fly.toml file generated for weathered-fog-7393 on 2022-01-08T17:17:35-05:00

app = "weathered-fog-7393"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  ASPNETCORE_ENVIRONMENT = "Development"
  ASPNETCORE_Kestrel__Certificates__Default__Path = "/https/aspnetappcert.pfx"
  ASPNETCORE_Kestrel__Certificates__Default__Password = "password"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
